# Generated by Django 2.2.8 on 2020-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='donations',
            field=models.FloatField(default=0),
        ),
    ]
