# Generated by Django 2.2 on 2019-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('status', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
