# Generated by Django 2.2.8 on 2019-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
