# Generated by Django 2.2.8 on 2019-12-31 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(default='to do', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
