# Generated by Django 2.2.8 on 2019-12-31 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='to do', max_length=20),
        ),
        migrations.AlterField(
            model_name='bug',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
