# Generated by Django 2.2.8 on 2019-12-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20191231_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='To Do', max_length=20),
        ),
    ]
