# Generated by Django 2.2.8 on 2020-03-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200302_2047'),
        ('bugs', '0003_auto_20191231_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
